- README.md
> Add style guidelines to README.MD file

- .storybook/addons.js
- .storybook/config.js
- package.json
- src/stories/index.js
- yarn.lock
> Add storybook.js

- src/components/About/AboutHeader.js
- src/components/AirComponents/AirHeader.js
- src/components/Header/JumbotronContent/AboutHeaderContent.js
- src/components/Header/JumbotronContent/AirHeaderContent.js
- src/components/Header/JumbotronContent/HardwareHeaderContent.js
- src/components/Header/JumbotronContent/JoinHeaderContent.js
- src/components/JoinNetwork/JoinHeader.js
- src/components/SensorsInfo/HardwareHeader.js
> Use props to display header text in all Jumbotron header sections

- package.json
- src/components/About/AboutHeader.js
- src/components/AirComponents/AirHeader.js
- src/components/Header/JumbotronContent/AboutHeaderContent.js
- src/components/Header/JumbotronContent/AirHeaderContent.js
- src/components/Header/JumbotronContent/HardwareHeaderContent.js
- src/components/Header/JumbotronContent/JoinHeaderContent.js
- src/components/JoinNetwork/JoinHeader.js
- src/components/SearchBar.js
- src/components/SensorsInfo/HardwareHeader.js
- yarn.lock
> Include search component in the air landing page

- src/components/About/AboutHeader.js
- src/components/About/Stories.js
- src/components/AirComponents/AirHeader.js
- src/components/Footer.js
- src/components/Header/JumbotronContent/AboutHeaderContent.js
- src/components/Header/JumbotronContent/AirHeaderContent.js
- src/components/Header/JumbotronContent/HardwareHeaderContent.js
- src/components/Header/JumbotronContent/JoinHeaderContent.js
- src/components/Header/Navbar.js
- src/components/JoinNetwork/JoinHeader.js
- src/components/SensorsInfo/HardwareHeader.js
> Add both router links and other relevant external link to the site

- src/components/CityComponents/Neighbourhood.js
- src/pages/air/City.js
> Add neighbourhood component for the city page

- src/components/CityComponents/DataTable.js
- src/components/CityComponents/SensorsDataReport.js
- src/pages/air/City.js
> Add statistic measure data info component 

- src/components/Maps/IframeComponent.js
- src/components/Maps/KenyaMap.js
- src/components/Maps/Nigeria.js
- src/components/Maps/Tanzania.js
- src/pages/air/City.js
> Add maps to the city page

- src/assets/css/App.css
- src/components/CityComponents/ArrowCards.js
- src/components/CityComponents/HostCard.js
- src/components/CityComponents/HostSensor.js
- src/components/CityComponents/HostSensorButtons.js
- src/pages/air/City.js
> Add host sensor component to the city page

- src/components/CityComponents/CallToAction.js
- src/components/Footer.js
- src/components/Hambuger/HambugerMenu.js
- src/components/Header/Navbar.js
- src/components/JoinNetwork/JoinSupport.js
> Add relevant links to all pages

- src/components/Footer.js
Current footer breaks in firefox.
> Fix footer break in Firefox

- src/components/AirComponents/AirHeader.js
- src/components/CityComponents/Header/CityHeader.js
- src/components/CityComponents/Header/CityMenuBar.js
- src/components/CityComponents/Header/CitySearchBar.js
- src/components/Header/JumbotronContent/AirHeaderContent.js
- src/components/SearchBar.js
- src/pages/air/City.js
- src/pages/air/index.js
+ Move all routing to `Page`s and away from `Component`s
+ Reuse `SearchBar` instead of recreating it in `CitySearchBar`
> [Hotfix] Reduce routing to Pages and not Components

- src/ScrollToTop.js
- src/components/AirComponents/IndoorOutdoor.js
- src/components/AirComponents/Issues.js
- src/components/CityComponents/Header/CityHeader.js
- src/components/CityComponents/HostSensors/ArrowCards.js
- src/components/CityComponents/SensorsQualityStats/DataTable.js
- src/components/Header/Navbar.js
- src/components/SearchBar.js
- Correct zIndex and position for select dropdown
- Fix Grid/Grid item & content mixups
- Fix/remove use of invalid properties
> [Hotfix] Fix Select Dropdown and Warnings

- .gitignore
- package.json
- yarn.lock
+ Update `.gitignore` to `vim,node,sass,django,jetbrains+all,visualstudiocode,macos,jekyll`.
+ Remove `eslint` direct dev dependency since it's included and must match the version defined by `create-react-app` script.
> Update Project Setup

- src/App.js
- src/assets/css/App.css
- src/assets/css/index.css
- src/components/Footer/Email.js
- src/components/Footer/index.js
- src/components/SocialMedia.js
> Minor improvements on the footer design 

- src/components/CityComponents/CallToAction.js
- src/pages/air/City.js
> Improve call to action cards

- src/components/SensorsInfo/HardwareInfo.js
- src/pages/air/HowSensorsWork.js
> Improve how sensors work hardware component

- src/assets/css/index.css
- src/components/AirComponents/GaugeChart.js
- src/components/AirComponents/IndoorOutdoor.js
- src/components/AirComponents/Issues.js
- src/components/Support.js
> Improve air landing page statistic section

- src/assets/css/App.css
- src/components/AirComponents/IndoorOutdoor.js
- src/components/CityComponents/CallToAction.js
- src/components/Footer/Email.js
- src/components/Footer/index.js
- src/components/Support.js
- src/pages/air/City.js
Small fixes around site UI, such as aligning width of components to match, etc.
> Update general site UI to match design

- src/components/Hambuger/HambugerMenu.js
- src/components/Hambuger/MenuButton.js
- src/components/Header/MenuBar.js
This PR has
- moved Logo position above the modal
- right aligned menu items
-  updated font style + size
- changed menu items list as per design
- adjusted & move Close button above the modal and aligned menu items right to it
Fixes #96
> Improve hamburger burger design

- src/components/CityComponents/SensorsQualityStats/DataTable.js
- src/components/CityComponents/SensorsQualityStats/QualityStats.js
> Improve quality statistic component

- src/components/About/AboutHeader.js
- src/components/About/Partners.js
- src/components/AirComponents/IndoorOutdoor.js
- src/components/AirComponents/Issues.js
- src/components/CityComponents/PollutionStats.js
- src/components/Footer/index.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
- src/components/Header/MenuBar.js
- src/components/JoinNetwork/JoinHeader.js
- src/components/SensorsInfo/HardwareHeader.js
- src/components/SensorsInfo/HardwareInfo.js
Removes place holders and add actual content to the site.
> [WIP] [#161471102] Update About contents

- package.json
- src/components/CityComponents/Header/CityHeader.js
- src/components/Footer/index.js
- src/components/Header/JumbotronContent/AboutHeaderContent.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
- src/components/Header/Navbar.js
- src/components/Maps/Kenya.js
- src/components/Maps/Nigeria.js
- src/components/Maps/Tanzania.js
- src/index.js
- src/pages/air/City.js
- yarn.lock
+ Remove horizontal scrollbars,
+ Remove the use of `ReactDOM.findDOMNode` which is discourage and it replace it with `Ref`,
+ Upgrade dependencies, especially `fontawesome` which had deprecated some of the libraries we were using, and
+ Fix uses of `Grid` & `Grid item`.
> [Chore] Fixes small but necessary UI, code and dependency issues

- src/App.js
- src/components/AirComponents/AirHeader.js
- src/components/CityComponents/Header/CityHeader.js
- src/components/CityComponents/Header/CityMenuBar.js
- src/components/Email.js
- src/components/Hambuger/HambugerMenu.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
- src/components/Header/JumbotronContent/AirHeaderContent.js
- src/components/Header/MenuBar.js
- src/components/Landing/Hero.js
- src/components/Logo.js
- src/components/SearchBar.js
- src/pages/air/City.js
- src/pages/air/index.js
To allow users not to be too harsh on our first version of sensors.AFRICA site, we should add a tiny banner at the top or some other way, that the site is in beta.
It should also probably point to a way to give feedback easily. E-mail?.
> 161644208 Add "beta" banner marker

- public/index.html
Site owner would want to collect various statistics about site visitors
> [161750529] Add Google analytics

- public/CNAME
Change domain to `sensors.africa`
> [161753686] Publish site to sensors.africa

- src/components/About/AboutHeader.js
- src/components/Air/Issues.js
- src/components/Footer/index.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
- src/components/HealthClimate/Burden.js
- src/components/HealthClimate/HealthAndClimateImpact.js
- src/components/HealthClimate/Sources.js
- src/components/JoinNetwork/JoinHeader.js
- src/components/SensorsInfo/HardwareHeader.js
- src/components/SensorsInfo/HardwareInfo.js
- src/components/Support.js
> Proof read site content for all components

- src/components/Hambuger/HambugerMenu.js
> Update resources link in the hambuger menu

- public/404.html
- src/components/DocumentHead/PageHeads.js
Add `404.html` (copy of `ìndex.html`) to handle `404` errors
> GitHub Pages 404 Issues [162264830]

- src/App.js
Use `process.env.PUBLIC_URL`  as `basename` in [Router](https://github.com/facebook/create-react-app/issues/1765#issuecomment-327615099)
> GitHub Pages 404 Issues [process.env.PUBLIC_URL] [162264830]

- src/App.js
Reverts CodeForAfricaLabs/sensors.AFRICA#168
> Revert "GitHub Pages 404 Issues [process.env.PUBLIC_URL] [162264830]"

- src/components/Support.js
> Fix support component links

- public/404.html
- src/components/DocumentHead/index.js
- src/pages/NotFound.js
Use @raflex/spa-github-pages for 404 page setup.
> Use rafrex/spa-github-pages for 404 page [162264830]

- src/pages/air/City.js
Fixes #162230958
Lagos
Dar-es-salaam
Nairobi
> Update pollution statistics data in the city pages

- src/components/City/HostSensors/HostSensorButtons.js
- src/pages/air/City.js
> Add host sensors button component to city page

- src/components/About/Stories.js
- src/components/Hambuger/HambugerMenu.js
- src/components/SocialMedia.js
> Change Medium links to tagged sensorsafrica

- src/components/Air/Issues.js
- src/components/Showcase/index.js
- src/pages/air/index.js
> Move showcase component to below the hero section of the city home page

- src/components/Air/IndoorOutdoor.js
> Update indoor outdoor component

- src/components/DataArchives/DataArchives.js
> Fix content layout on the data page

- src/pages/NotFound.js
1. Make Go Back button more visible, and
2. Redirect to home when previous is empty
Normal (left) & on hoover (right)
> Improve 404 Page [163317945]

- src/components/SocialMedia.js
> Add facebook link

- src/components/DataArchives/DataArchives.js
> Update archive link in the data page

- src/assets/css/App.css
- src/components/City/Header/CityHeader.js
- src/components/City/SensorsQualityStats/DataTable.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/DigitalGauge.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
- src/components/Logo.js
- src/components/SearchBar.js
- src/components/SocialMedia.js
- src/pages/air/City.js
Review and fix pre-site launch issues
----------------------------------------------
----------------------------------------------
Multiple other small fixes in code.
> Pre Site Launch Review

- src/components/City/SensorsQualityStats/DataTable.js
- src/components/City/SensorsQualityStats/index.js
- src/components/PartnerLogos.js
Remove extra space and horizontal scrolling.
Fixed on the left, current on the right.
> [Fix] Data table mobile view

- src/components/PartnerLogos.js
> Fix partner logo component

- .env
- src/App.js
- src/api/index.js
- src/components/City/HostSensors/ShareButton/Embed.js
- src/components/City/HostSensors/ShareButton/index.js
- src/components/Embeds/AirGauge.js
- src/components/Embeds/AirGraph.js
- src/components/Embeds/AirMap.js
- src/components/Embeds/index.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
- src/pages/air/City.js
This allows to get:
-  the sensor map using the endpoint `https://sensors.africa/embeded/air/map?city=<city>`.
example:
```html
<iframe src="https://localhost:3001/embeded/air/map?city=nairobi" height='500px' width='800px'></iframe>
```
-  the weekly data graph using the endpoint `https://sensors.africa/embeded/air/graph?city=<city>`.
example:
```html
<iframe src="https://localhost:3001/embeded/air/graph?city=nairobi" height='500px' width='800px'></iframe>
```
-  the dial component using the endpoint `https://sensors.africa/embeded/air/dial?city=<city>`.
example:
```html
<iframe src="https://localhost:3001/embeded/air/dial?city=nairobi" height='400px' width='100%'></iframe>
```
Fixes # (issue)
> sensors.AFRICA embeds

- src/components/About/AboutContent/Content.js
- src/components/About/AboutContent/index.js
- src/pages/About.js
- src/pages/air/About.js
> Add sensors.AFRICA about us page content

- src/components/About/Stories.js
- src/components/Hambuger/HambugerMenu.js
- src/components/SocialMedia.js
> [sensors.AFRICA][Site]Update medium link

- src/components/Header/JumbotronContent/AirHeaderContent.js
- src/components/Header/Navbar.js
- src/components/SearchBar.js
> [sensor.AFRICA][Site] Make navigation bar sticky

- src/components/City/Header/CityHeader.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/NeedlePointer.js
- src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
> [Site] Fix the dial component layout

- src/components/About/Air/Header.js
- src/components/About/Header.js
> [sensors.AFRICA][Site]Add info to about us component

- src/components/About/Air/Header.js
- src/components/About/Header.js
> Fix attribution content

- src/components/About/Air/Header.js
- src/components/About/Header.js
> Minor fix on about page

- src/components/Embeds/AirMap.js
- src/components/SensorMap/IframeComponent.js
Whenever the location change, we need to make sure the map iframe is updated as well.
Previous Design:
Current
> Update map iframe on location change

- src/components/Hambuger/HambugerMenu.js
Add HARDWARE menu item & sort menus alphabetically
> Add HARDWARE menu item & sort menus alphabetically

- src/components/About/Staff.js
Fix staff emails
Current: 
Implementation:
> Fix staff emails

- src/components/City/SensorsQualityStats/DataTable.js
Fix units of measurement for parameters reported.
> fix units of measurement

- src/api/index.js
- src/components/Embeds/AirMap.js
- src/components/SensorMap/index.js
- src/pages/air/City.js
> [WIP][sensors.AFRICA] Embed new map to site

- src/api/index.js
Third Pr on  #168072108
Current: 
Fix:
> Fix Nairobi map display

- src/components/City/HostSensors/ShareButton/SocialMediaButtons.js
> Fix Share Dialog Link

- src/components/DataArchives/DataArchives.js
- src/components/Showcase/StoryList.js
> Update sensors.AFRICA docs + fix showcase section

- src/api/index.js
New api requires interval specification
Bug:
Fixed:
> Get daily averages to fix wonky graph

- src/components/SensorMap/IframeComponent.js
- src/components/SensorMap/index.js
Remove scrollbars on city sensor map
> [Hotfix] City Sensor Map

- package.json
- yarn.lock
Add `react-helmet` until a switch to `next/head` is complete.
N/A
> [Hotfix] react-helmet

- .babelrc
- .gitignore
- README.md
- jsconfig.json
- src/components/Embeds/AirGauge.js
- src/components/Embeds/AirGraph.js
- src/components/Embeds/AirMap.js
- src/lib/gtag.js
- src/pages/_app.js
- src/pages/_document.js
- src/pages/embeded/air/dial.js
- src/pages/embeded/air/graph.js
- src/pages/embeded/air/map.js
- yarn.lock
> [Fix] Analytics + SSR Embeds

- src/components/About/Staff.js
- yarn.lock
> [Hotfix] Update Email details

- src/api/index.js
- src/components/DocumentHead/PageHeads.js
- src/components/SearchBar.js
- src/pages/air/city/[id].js
Add cities information
Fixes # (issue)
> Add nairobi + kisumu data

- src/pages/air/city/[id].js
This converts the Serversideprops to static props with static paths
Fixes # (N/A)
> [Fix] Server Side Generate page

- .dockerignore
- .github/workflows/main.yml
- Dockerfile
- contrib/dokku/Dockerfile
- next.config.js
- package.json
Adds Docker image for sensorsAfrica and deploys to dokku
> Adds Dokku deployment

- src/components/About/Staff.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
I corrected my email; changed it from ahmed@codeforafrica.org to usman@codeforafrica.org.
> changed usman's email

- contrib/dokku/Dockerfile
- package.json
- src/components/Header/MenuBar.js
- src/components/Header/Navbar.js
- src/components/SocialMedia.js
> A link to our github repo

- contrib/dokku/Dockerfile
- package.json
- src/components/Showcase/index.js
Updated the showcase section header (text) to a phrase more descriptive of the stories we publish
> updated the showcase sections header text

- contrib/dokku/Dockerfile
- package.json
- src/components/About/Staff.js
Edited some text on the staff profile section
> edited text on staff profile
